env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}
name: Java CI
on: push
jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: chmod +x ci/build-app.sh && ci/build-app.sh
      - name: Upload Repo
        uses: actions/upload-artifact@v2
        with:
          name: code-done
          path: .
      - name: Test
        run: chmod +x ci/unit-test-app.sh && ci/unit-test-app.sh
  Docker-image:
    needs: [Build]
    runs-on: ubuntu-latest
    container: docker:latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: code-done
          path: .
      - run: export GIT_COMMIT="GA-$GITHUB_SHA"
      - run: chmod +x ci/build-docker.sh 
      - run: GIT_COMMIT="GA-$GITHUB_SHA" sh ./ci/build-docker.sh
      - run: chmod +x ci/push-docker.sh 
      - run: GIT_COMMIT="GA-$GITHUB_SHA" sh ./ci/push-docker.sh
  Component-test:
    needs: [Docker-image]
    runs-on: ubuntu-latest
    container: docker:latest
    steps:
      - uses: actions/checkout@v2
      - run: chmod +x ci/component-test.sh && sh ./ci/component-test.sh
