env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}
name: Java CI
on: push
jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: chmod +x ci/build-app.sh && ci/build-app.sh
      - name: Test
        run: chmod +x ci/unit-test-app.sh && ci/unit-test-app.sh
      - run: chmod +x ci/build-docker.sh 
      - run: GIT_COMMIT="GA-$GITHUB_SHA" sh ./ci/build-docker.sh
      - run: chmod +x ci/push-docker.sh 
      - run: GIT_COMMIT="GA-$GITHUB_SHA" sh ./ci/push-docker.sh
      - run: chmod +x ci/component-test.sh && ./ci/component-test.sh
